### ISSUE TITLE
On Removing Backbutton 

### ISSUE THREAD

**Issue by sunil209** [jcubic/tagger#12] opened 2021-02-10 19:21 UTC
On Removing the by back button, string is not getting removed from the main associated input field. Can you please help me out

**Comment by jcubic** [comment] 2021-02-10 19:44
You mean backspace key? By back button you usually refer to browser back button. Do you mean the first the key or the second?

If you mean backspace key, then it right now remove the tag. That's default behavior.

**Comment by sunil209** [comment] 2021-02-10 19:55
Hi @jcubic , I mean backspace key. Yeah it remove the tag correct but value stay in the input field. till then I do`t click on cross icon. Due to which I am facing validation issue.

Eg:

I have enter three tags and then by backspace key i removed all the tags but in the input fields all three values stay in.

**Comment by sunil209** [comment] 2021-02-10 19:59
Please check below screenshot.

![image](https://user-images.githubusercontent.com/4804763/107564535-8dd4be00-6c08-11eb-939e-3f9dd4e8fe6f.png)

**Comment by jcubic** [comment] 2021-02-10 20:25
Thanks for the report, It's fixed now. You can check if it works for you and I'll publish to npm.
Besides the fix I've also kind of made breaking change, the value no longer have space after comma, I think it was bad idea.

**Comment by sunil209** [comment] 2021-02-10 20:35
Thanks a lot @jcubic for quick help. Once push to npm please let me know as I am using via npm cannot directly update the library.

Thanks

**Comment by jcubic** [comment] 2021-02-10 20:42
You can try using [npm link](https://docs.npmjs.com/cli/v6/commands/npm-link), before I publish new version. I think it's right link.

**Comment by ghost** [comment] 2021-02-11 08:36
Hi @jcubic , This works but Found one more issue. 
Suppose I type word in the field and without enter, space or comma I go out to press the submit button. Then it does not fill the value in the main input field due to which even values exist but it still render the empty errror message. On submit

**Comment by jcubic** [comment] 2021-02-11 10:46
Can you create another issue and explain more how to reproduce it? Maybe create demo, because I don't quite understand.

**Comment by ghost** [comment] 2021-02-11 11:25
Sure, Meanwhile you can push this fix to npm If possible

**Comment by jcubic** [comment] 2021-02-11 12:41
Will publish to npm version 0.4.0 with one bug (this one) and two features (one your request).

**Closed as completed by jcubic** 2021-02-11 12:41 UTC
Labels: bug
